# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
#      - test-3.7
#      - test-3.6
      - test-3.5-django1.11
#      - test-3.4
#      - test-2.7

#django-versions:
#  - &django2.1 2.1
#  - &django2.0 2.0
#  - &django1.11 1.11
jobs:
  test-3.7-django2.1: &test-template
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7-jessie

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]
            pip install psycopg2

      - run:
          name: install django version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install django==1.11

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            py.test --cov=graphene_django graphene_django examples

      - store_artifacts:
          path: test-reports
          destination: test-reports
#  test-3.7-django2.0:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.7-jessie
#  test-3.6-django2.1:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.6-jessie
#  test-3.6-django2.0:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.6-jessie
#  test-3.5-django2.1:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.5-jessie
#  test-3.5-django2.0:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.5-jessie
  test-3.5-django1.11:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
#  test-3.4-django2.0:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.4-jessie
#  test-2.7:
#    <<: *test-template
#    docker:
#      - image: circleci/python:2.7-jessie