# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  test-3_7-django2_1: &test-template
    parameters:
      django_version:
        type: string
        default: "2.1"
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7-rc-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .[test]
            pip install psycopg2

      - run:
          name: install django version
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install django==<< parameters.django_version >>

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            py.test --cov=graphene_django graphene_django examples
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3_7-django2_0:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-rc-node
  test-3_6-django2_1:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  test-3_6-django2_0:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  test-3_5-django2_1:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-3_5-django2_0:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-3_5-django1_11:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-3_4-django2_0:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie
  test-3_4-django1_11:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie
  test-2_7-django1_11:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie

workflows:
  version: 2
  test:
    jobs:
      - test-3_7-django2_1:
          django_version: "2.1"
      - test-3_7-django2_0:
          django_version: "2.0"
      - test-3_6-django2_1:
          django_version: "2.1"
      - test-3_6-django2_0:
          django_version: "2.0"
      - test-3_5-django2_1:
          django_version: "2.1"
      - test-3_5-django2_0:
          django_version: "2.0"
      - test-3_5-django1_11:
          django_version: "1.11"
      - test-3_4-django2_0:
          django_version: "2.0"
      - test-3_4-django2_0:
          django_version: "2.0"
      - test-3_4-django1_11:
          django_version: "1.11"
      - test-2_7-django1_11:
          django_version: "1.11"